server:
  port: 9090
jwt.aws.userPoolId: us-east-1_DUfDYLnmA
jwt.aws.region: us-east-1
---
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
     
      routes:
        - id: mdm
          uri: http://localhost:8090/
          predicates:
            - Path=/mdm/**
         
        - id: assessment
          uri: http://localhost:8088/
          predicates:
            - Path=/assessment/**
            

