server:
  port: 9090
jwt.aws.userPoolId: ${user_pool_id}
jwt.aws.region: ${region}
---
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
     
      routes:
        - id: mdm
          uri: ${mdm_url}
          predicates:
            - Path=/mdm/**
         
        - id: assessment
          uri: ${assessment_url}
          predicates:
            - Path=/assessment/**
            

