version: '3'
services:
  onlinetutorialdbnew:
    container_name: onlinetutorialdbnew
    restart: always
    image: mysql:8.0.30
    ports:
    - 3307:3307
    expose:
      - 3307 
    environment:
       - MYSQL_USER=testpass
       - MYSQL_PASSWORD=testpass
       - MYSQL_ROOT_PASSWORD=testpass
       - MYSQL_DATABASE=shikshadb
       - MYSQL_TCP_PORT=3307
    volumes:
      - onlinetutorialdbvol:/var/lib/mysql
  apigateway:
    container_name: apigateway
    image: pavithravasudevan/spring-cloud-gateway:0.0.1
    ports:
      - 9090:9090
    environment:
      - spring.cloud.gateway.routes[0].id=mdm
      - spring.cloud.gateway.routes[0].predicates[0]=Path=/mdm/**
      - spring.cloud.gateway.routes[0].uri=http://mdm/
      - spring.cloud.gateway.routes[1].id=assessment
      - spring.cloud.gateway.routes[1].predicates[0]=Path=/assessment/**
      - spring.cloud.gateway.routes[1].uri=http://studentassessment/
  mdm:
    container_name: mdm
    image: pavithravasudevan/administration-service:0.0.1
    ports:
      - 8090:8090
    depends_on:
      - onlinetutorialdbnew
    environment:
      - spring.datasource.url=jdbc:mysql://onlinetutorialdbnew:3307/shikshadb?user=testpass&password=testpass&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
  studentassessment:
    container_name: studentassessment
    image: pavithravasudevan/assessment-service:0.0.1
    ports:
      - 8088:8088
    depends_on:
      - onlinetutorialdbnew
    environment:
      - spring.datasource.url=jdbc:mysql://onlinetutorialdbnew:3307/shikshadb?user=testpass&password=testpass&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - restapi.mdm.url=http://mdm/
      - AWS_REGION=us-east-1

volumes:
  onlinetutorialdbvol:
  
  
  