version: '3'
services:
  mysql:
    container_name: onlinetutorialdb
    restart: always
    image: mysql:8.0.30
    ports:
    - 3307:3307
    expose:
      - 3307 
    environment:
       - MYSQL_USER=testpass
       - MYSQL_PASSWORD=testpass
       - MYSQL_ROOT_PASSWORD=testpass
       - MYSQL_DATABASE=shikshadb
       - MYSQL_TCP_PORT=3307
    volumes:
      - onlinetutorialdbvol:/var/lib/mysql
  apigateway:
    container_name: apigateway
    image: pavithravasudevan/spring-cloud-gateway:0.0.1
    ports:
      - 9090:9090
    environment:
      - spring.cloud.gateway.routes[0].id=mdm
      - spring.cloud.gateway.routes[0].predicates[0]=Path=/mdm/**
      - spring.cloud.gateway.routes[0].uri=http://mdm:8090/
      - spring.cloud.gateway.routes[1].id=assessment
      - spring.cloud.gateway.routes[1].predicates[0]=Path=/assessment/**
      - spring.cloud.gateway.routes[1].uri=http://studentassessment:8088/
  mdm:
    container_name: mdm
    image: pavithravasudevan/administration-service:0.0.1
    ports:
      - 8090:8090
    depends_on:
      - mysql
    env_file:
      - ./env/mdm.env
  studentassessment:
    container_name: studentassessment
    image: pavithravasudevan/assessment-service:0.0.1
    ports:
      - 8088:8088
    depends_on:
      - mysql
    env_file:
      - ./env/student-assessment.env

volumes:
  onlinetutorialdbvol:
  
  
  