apiVersion: v1
kind: ConfigMap
metadata:
  name: apigateway-config
data:  
    mdm_url: http://mdm.default.svc.cluster.local:8090/    
    assessment_url: http://assessment.default.svc.cluster.local:8088/
    jwt.aws.userPoolId: us-east-1_d7gTXDzXK
---
apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    app: apigateway
  name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway  
  template:
    metadata:      
      labels:
        app: apigateway
    spec:
      
      containers:
      - image: pavithravasudevan/spring-cloud-api-gateway-unsecured:0.0.1
        name: apigateway
        resources:
          requests:
            memory: "600Mi"
            cpu: "400m"
          limits:
            memory: "600Mi"
            cpu: "400m"       
        
       
        envFrom:
        - configMapRef:
            name: apigateway-config
       
---
apiVersion: v1
kind: Service
metadata: 
  labels:
    app: apigateway
  name: apigateway
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health/readiness
spec:
  ports:
  - name: 9090-9090
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: apigateway
  type: NodePort
status:
  loadBalancer: {}