apiVersion: v1
kind: ConfigMap
metadata:
  name: assessment-config
data:  
    spring.datasource.url: jdbc:mysql://mysql.default.svc.cluster.local:3306/shikshadb?user=testpass&password=testpass&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    restapi.mdm.url: http://mdm.default.svc.cluster.local:8090/
    AWS_REGION: us-east-1
    kubernetes.profile: "Y"
  

---
apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    app: assessment
  name: assessment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assessment  
  template:
    metadata:      
      labels:
        app: assessment
    spec:
      serviceAccountName: sqs-access
      containers:
      - image: pavithravasudevan/student-assessment-service:0.0.1
        name: assessment
        imagePullPolicy: Always
        resources:
          requests:
            memory: "700Mi"
            cpu: "400m"
          limits:
            memory: "800Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: assessment-config
       
---
apiVersion: v1
kind: Service
metadata: 
  labels:
    app: assessment
  name: assessment
spec:
  ports:
  - name: 8088-8088
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: assessment
  type: ClusterIP
status:
  loadBalancer: {}