apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:  
   
    REACT_APP_CLIENT_ID: 4d0rspobol474rft7nq57krjjq
    REACT_APP_USER_POOL_ID: us-east-1_d7gTXDzXK
    REACT_APP_SERVER_URL: https://shiksha.saaralkaatru.com/

---
apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend  
  template:
    metadata:      
      labels:
        app: frontend
    spec:
      
      containers:
      - image: pavithravasudevan/shiksha-frontend:0.0.1
        name: frontend       
        envFrom:
        - configMapRef:
            name: frontend-config
       
---
apiVersion: v1
kind: Service
metadata: 
  labels:
    app: frontend
  name: frontend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  type: NodePort
status:
  loadBalancer: {}