version: '3'
services:
  mysql:
    container_name: onlinetutorialdb
    restart: always
    image: mysql:8.0.30
    ports:
    - 3307:3307
    expose:
      - 3307 
    environment:
       - MYSQL_USER=testpass
       - MYSQL_PASSWORD=testpass
       - MYSQL_ROOT_PASSWORD=testpass
       - MYSQL_DATABASE=shikshadb
       - MYSQL_TCP_PORT=3307
    volumes:
      - onlinetutorialdbvol:/var/lib/mysql
volumes:
  onlinetutorialdbvol:
  
  
  