apiVersion: v1
kind: ConfigMap
metadata:
  name: assessment-config
data:  
    spring.datasource.url: jdbc:mysql://{{.Values.dbConnectionStringParams.serviceName}}.default.svc.cluster.local:{{.Values.ports.mysql}}/{{.Values.dbConnectionStringParams.dbName}}?user={{.Values.dbConnectionStringParams.userName}}&password={{.Values.dbConnectionStringParams.password}}&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    restapi.mdm.url: http://mdm.default.svc.cluster.local:{{.Values.ports.mdm}}/
    AWS_REGION: {{.Values.aws.region}}
    kubernetes.profile: "Y"
  

---
apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    app: assessment
  name: assessment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assessment  
  template:
    metadata:      
      labels:
        app: assessment
    spec:
      serviceAccountName: {{.Values.serviceAccountName.assessment}}
      containers:
      - image: pavithravasudevan/student-assessment-service:0.0.1
        name: assessment
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: assessment-config
       
---
apiVersion: v1
kind: Service
metadata: 
  labels:
    app: assessment
  name: assessment
spec:
  ports:
  - name: 8088-8088
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: assessment
  type: ClusterIP
status:
  loadBalancer: {}