apiVersion: v1
kind: ConfigMap
metadata:
  name: mdm-config
data:  
    spring.datasource.url: jdbc:mysql://{{.Values.dbConnectionStringParams.serviceName}}.default.svc.cluster.local:{{.Values.ports.mysql}}/{{.Values.dbConnectionStringParams.dbName}}?user={{.Values.dbConnectionStringParams.userName}}&password={{.Values.dbConnectionStringParams.password}}&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false    
    AWS_REGION: {{.Values.aws.region}}
    kubernetes.profile: "Y"
    jwt.aws.userPoolId: {{.Values.aws.cognito.userPoolId}}
    cognito.app.clientid: {{.Values.aws.cognito.appClientId}}
    

---
apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    app: mdm
  name: mdm
spec:
  replicas: 1
 
  selector:
    matchLabels:
      app: mdm  
  template:
    metadata:      
      labels:
        app: mdm
    spec:
      serviceAccountName: {{.Values.serviceAccountName.mdm}}
      containers:
      - image: {{.Values.image.repositoryName}}/administration-service:0.0.1
        name: mdm
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: mdm-config
       
---
apiVersion: v1
kind: Service
metadata: 
  labels:
    app: mdm
  name: mdm
spec:
  ports:
  - name: 8090-8090
    port: {{.Values.ports.mdm}}
    protocol: TCP
    targetPort: 8090
  selector:
    app: mdm
  type: ClusterIP
status:
  loadBalancer: {}