apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:  
   
    REACT_APP_CLIENT_ID: {{.Values.aws.cognito.userPoolId}}
    REACT_APP_USER_POOL_ID: {{.Values.aws.cognito.appClientId}}
    REACT_APP_SERVER_URL: shiksha.{{.Values.ingress.domainName}} 

---
apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend  
  template:
    metadata:      
      labels:
        app: frontend
    spec:
      
      containers:
      - image: {{.Values.image.repositoryName}}/shiksha-frontend:0.0.1
        name: frontend       
        envFrom:
        - configMapRef:
            name: frontend-config
       
---
apiVersion: v1
kind: Service
metadata: 
  labels:
    app: frontend
  name: frontend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  ports:
  - name: 80-80
    port: {{.Values.ports.frontend}}
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  type: NodePort
status:
  loadBalancer: {}