loki:
  serviceName: "logs-prod-us-central1.grafana.net"
  servicePort: 443
  serviceScheme: https
  user: apavithraa
  password: eyJrIjoiNTUyYTM0MmMzZmY4NzcyNDRkNDcwY2MzMDQ4ZjA0MzRjN2Q1NzdkMSIsIm4iOiJwaWxscyIsImlkIjo3MjE1MzB9
extraScrapeConfigs:
  - job_name: journal
    journal:
      path: /var/log/journal
      max_age: 12h
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__hostname']
        target_label: 'hostname'
extraVolumes:
  - name: journal
    hostPath:
      path: /var/log/journal
extraVolumeMounts:
  - name: journal
    mountPath: /var/log/journal
    readOnly: true
pipelineStages:
- docker:
- match:
    selector: '{app="eventrouter"}'
    stages:
    - json:
        expressions:
          namespace: event.metadata.namespace
    - labels:
        namespace: ""
config:
  clients:
    - url: http://loki-loki-distributed-gateway/loki/api/v1/push