dbConnectionStringParams:
  serviceName: shikshaapp-mysql
  dbName: shikshadb
  userName: testpass
  password: testpass
image:
  repositoryName: pavithravasudevan
aws:
  cognito:
    userPoolId: us-east-1_d7gTXDzXK
    appClientId: 4d0rspobol474rft7nq57krjjq
  region: us-east-1
ports:
    apigateway: 9090
    mdm: 8090
    assessment: 8088
    mysql: 3306
    frontend: 80
ingress:
  domainName: saaralkaatru.com
serviceAccountName:
  mdm: mdm
  assessment: assessment

mysql:
  auth:
    database: shikshadb
    username: testpass
    password: testpass
    rootPassword: testpass
  volumePermissions:
    enabled: true
  primary:
    persistence:
      size: 4Gi
      existingClaim: ebs-mysql-pv-claim
